### ISSUE TITLE
How to implement authorisation with an external authority?

### ISSUE THREAD

**Issue by ntaylor-barnett** [ma-ha/easy-web-gui#8]
I've been watching this project for a while and I am really impressed with it. I am keen to try and make use of it, but I need to validate its viability first. One thing I am trying to achieve is to get some kind of authorization going. I don't want to manage my own username/password stuff and would love if we could easily do something like github authentication or something. 

Do you have any thoughts or examples on how I might implement that? My current alternative is to hide it in our cluster and restrict access using kube proxying, but if we can get something a bit slicker than that, it would make things a lot easier.

**Comment by ma-ha** [comment]
Hi, thanks for your feedback. 
Beside simple user/password basic-auth, an OpenID Connect client implementation also available, so you should be able to use any OpenID Identity provider (see https://openid.net/certification/) and so you can configure also the use of Social Media accounts etc
- code example: https://github.com/ma-ha/easy-web-app/tree/master/examples/openid
- online demo: http://mh-svr.de/pong_dev/index.html?layout=tests/sec2 (only bare login/logout test using the "Login" button on the upper left) This example uses Auth0.com as identity provider.
Everything is Open Source and all functionality is implemented as "plug-ins" (openid is this module: https://github.com/ma-ha/rest-web-ui/tree/master/html/modules/pong-security2) other identity provider plugins (e.g GitHub) can be implemented, if required.
Hope this helps. 
Kind regards, Markus
