### ISSUE TITLE
Module for basic results formatting?

### ISSUE THREAD

**Issue by ntaylor-barnett** [ma-ha/easy-web-gui#9]
The table formatting is really neat, however I have a use case for some really simple data formatting. In this case, I just have a single JSON object as a result that I would like to display its properties. Problem is that I cannot see a module that can do this cleanly for me. I can see that there is the markdown one that I have done a simple display like this:

```
app.get('/md/:page', async function (req, res) {
  switch(req.params.page) {
    case 'info':
      var sts = new aws.STS();
      sts.getCallerIdentity().promise().then(callerIdentity => {
        res.send(
          `# Connection Information
          Account: ${callerIdentity.Account}
          ARN: ${callerIdentity.Arn}
          User: ${callerIdentity.UserId}
          
          # Current Configuration
          ${JSON.stringify(currconfig)}
          `
        )
      })
    break;
  }
})
```
annoyingly though, i have had to change the resftul response to be the markdown I want displayed, instead of the original JSON based response that i originally had. It is okay, but it would be nicer if there was a module that allowed me to define how to format this kind of stuff, perhaps even being markdown itself?

My main challenge is that I am now going to implement a POST method that will hit a different service and get its response, but that response could be anything, and it definitely won't be an array of results. Most likely, I am going to handle the call to this other API by using the neat logic here with an "app.post" to hit it and I can have that deal with the response that might come back, but (at least in my head) that response i would format would be a JSON response, and i would like to have a neat way to present that data in a similar way that I did with that markdown. 

Do you already have some kind of capability in place for what I am trying to achieve here, or is this something that a new "module" would be needed for?

**Comment by ma-ha** [comment]
Hi,
you can do basic formatting JSON data in at least two ways: 

1. using the **markdown** (see https://github.com/ma-ha/easy-web-app/blob/master/examples/markdown/index.js) module or the **html** view, and crunch the format in the backend API, but this is not the ideal way
2. I suggest to use the **list** module (see https://github.com/ma-ha/easy-web-app/tree/master/examples/list), which basically creates a lot of HTML DIVs (also hierarchically) and puts your data in. You can use the full power of CSS here. Only draw back here: List expects an array from the API, even if it's only one object -- but should not too hard to code that ;-)
